// Public original UI + openly addressable shared studio adapter.
// The studio and its APIs use one shared workspace and require no login, cookie or access token.
import { listPage, articlePage, shell } from './ssul-render.mjs';
import source from './ssul-source-data.mjs';
const API='https://wvwoqqfizgbhvdzlqscc.supabase.co/functions/v1/ssul_public';
const STUDIO_API='https://wvwoqqfizgbhvdzlqscc.supabase.co/functions/v1/ssul_studio';
const PUBLIC_KEY='sb_publishable_iLtSrF52sRfzalwcR4Nt-w_dJiU2q16';
const security={'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','X-SSUL-UI':'original-live-source','X-SSUL-Backend':'supabase'};
const jsonHeaders={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
export function dbId(value){const id=String(value??'');return /^0*[1-6]$/.test(id)?String(Number(id)):id}
export function storyUrl(id){const value=dbId(id);return `/stories/${encodeURIComponent(/^[1-6]$/.test(value)?value.padStart(3,'0'):value)}/`}
function html(text,status=200,extra={}){return new Response(text,{status,headers:{...security,...extra}})}
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{...jsonHeaders,...extra}})}
async function data(url,options={}){const response=await fetch(url,{...options,headers:{apikey:PUBLIC_KEY,...options.headers},signal:AbortSignal.timeout(15000)});let body;try{body=await response.json()}catch{throw new Error('Public API returned invalid JSON')}if(!response.ok||!body.ok)throw new Error('Public API unavailable: '+response.status);return body}
function originalContent(p){let old=source.previousSeeds.find(x=>x.id===dbId(p.id));if(old&&dbId(p.id)==='2')old={...old,beforeContent:'12년을 친구로 지낸 사람이었다. 내 결혼식에는 가족 일이 생겨 정말 미안하다며 오지 못한다고 했다.\n\n서운했지만 이해하려 했다. 그런데 우연히 본 사진 한 장에서 그 친구가 다른 결혼식장에 있었다.',afterContent:'처음에는 날짜를 잘못 본 줄 알았다. 사진을 확대해 보고, 올라온 시간을 다시 확인했다.\n\n내 결혼식이 끝난 다음 날도 아니었다. 같은 날, 다른 시간대 식장이었다.\n\n사진 속 표정이 너무 밝아서 오히려 무슨 말을 해야 할지 모르겠더라.'};const actual=source.originals.find(x=>x.id===dbId(p.id));if(!old||!actual||p.title!==old.title||p.beforeContent!==old.beforeContent||p.afterContent!==old.afterContent||p.gateLine!==old.gateLine)return p;return{...p,beforeContent:actual.beforeContent,afterContent:actual.afterContent,gateLine:actual.gateLine,hook:actual.hook,coverDetail:actual.coverDetail,fadeHeight:actual.fadeHeight}}
function hashtagText(value){return Array.isArray(value)?value.filter(tag=>typeof tag==='string'&&tag.trim()).map(tag=>tag.trim()).join(' '):String(value||'')}
function siteContent(p){const value=originalContent(p||{}),raw=dbId(value.id),fade=Number(value.fadeHeight??value.fade_height??180);return{id:/^[1-6]$/.test(raw)?raw.padStart(3,'0'):raw,title:String(value.title||''),category:String(value.category||'일상'),teaser:String(value.teaser||''),beforeContent:String(value.beforeContent||''),afterContent:String(value.afterContent||''),hook:String(value.hook||''),coverDetail:String(value.coverDetail||''),caption:String(value.caption||''),hashtags:hashtagText(value.hashtags),fadeHeight:Math.max(80,Math.min(300,Number.isFinite(fade)?fade:180)),gateLine:String(value.gateLine||''),views:Number(value.views??value.view_count??0)}}
async function studioCall(payload){const response=await fetch(STUDIO_API,{method:'POST',headers:{apikey:PUBLIC_KEY,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(170000)});let body;try{body=await response.json()}catch{throw Object.assign(new Error('제작실 서버 응답을 읽지 못했어요.'),{status:502})}if(!response.ok||!body.ok)throw Object.assign(new Error(body.error||'제작실 요청을 처리하지 못했어요.'),{status:response.status});return body}
async function requestBody(request){try{return await request.json()}catch{return{}}}
function arrayB64(ab){const a=new Uint8Array(ab);let s='';for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(s)}
async function studioApi(request,path){const method=request.method,u=new URL(request.url);
  if(path==='/api/settings'){if(method==='GET')return json(await studioCall({action:'settings_get'}));if(method==='POST'){const b=await requestBody(request);return json(await studioCall({action:'settings_save',key:b.key,model:b.model}));}}
  if(path==='/api/writing-prompt'){if(method==='GET')return json(await studioCall({action:'writing_prompt_get'}));if(method==='PUT'){const b=await requestBody(request);return json(await studioCall({action:'writing_prompt_save',prompt:b.prompt,revision:b.revision}));}}
  if(path==='/api/drafts'&&method==='GET')return json(await studioCall({action:'drafts_list'}));
  const versions=path.match(/^\/api\/drafts\/([\w-]+)\/versions$/);if(versions&&method==='GET')return json(await studioCall({action:'versions_list',id:versions[1]}));
  const publish=path.match(/^\/api\/drafts\/([\w-]+)\/publish$/);if(publish&&method==='POST'){const b=await requestBody(request);return json(await studioCall({action:'publish',id:publish[1],revision:b.revision}));}
  const draft=path.match(/^\/api\/drafts\/([\w-]+)$/);if(draft){if(method==='GET')return json(await studioCall({action:'draft_get',id:draft[1]}));if(method==='PUT'){const b=await requestBody(request);return json(await studioCall({action:'draft_save',id:draft[1],data:b.data,revision:b.revision,reason:b.reason}));}}
  if(path==='/api/jobs'&&method==='GET')return json(await studioCall({action:'jobs_list'}));
  const candidate=path.match(/^\/api\/jobs\/([\w-]+)\/candidate$/);if(candidate&&method==='GET')return json(await studioCall({action:'job_candidate',id:candidate[1]}));
  if(path==='/api/jobs'&&method==='POST'){const b=await requestBody(request),encoder=new TextEncoder();const stream=new ReadableStream({start(controller){let open=true;const send=value=>{if(open)try{controller.enqueue(encoder.encode(JSON.stringify(value)+'\n'))}catch{open=false}};send({type:'started',jobId:b.jobId});let progressMessage='클로드가 요청한 내용을 작성하고 있어요.';send({type:'progress',message:progressMessage});const timer=setInterval(()=>send({type:'progress',message:progressMessage}),15000);(async()=>{try{const out=await studioCall({action:'job_run',...b});progressMessage='Claude 작업을 완료했어요. 결과를 확인해 주세요.';send({type:'progress',message:progressMessage});send({type:'done',jobId:out.id,result:out.result,usage:out.usage,model:out.model,calls:out.calls,promptUsage:out.promptUsage,promptRevision:out.promptRevision,baseData:out.baseData,target:out.target})}catch(error){send({type:'failed',jobId:b.jobId,message:error?.message||'클로드 작업을 완료하지 못했어요.'})}finally{clearInterval(timer);if(open)try{controller.close()}catch{}}})()}});return new Response(stream,{headers:{'Content-Type':'application/x-ndjson; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
  if(path==='/api/source'&&method==='POST'){const b=await requestBody(request);return json(await studioCall({action:'source_read',url:b.url}));}
  if(path==='/api/images'&&method==='POST'){const mime=request.headers.get('Content-Type')||'',ab=await request.arrayBuffer();if(ab.byteLength>4*1024*1024)return json({error:'이미지는 4MB 이하로 올려 주세요.'},413);return json(await studioCall({action:'image_upload',name:u.searchParams.get('name')||'이미지',mime,base64:arrayB64(ab)}));}
  const image=path.match(/^\/api\/images\/([\w-]+)$/);if(image&&method==='GET'){const out=await studioCall({action:'image_url',id:image[1]});return Response.redirect(out.url,302)}
  return json({error:'요청한 제작실 기능을 찾을 수 없어요.'},404);
}
export default{async fetch(request,env){const url=new URL(request.url),path=url.pathname;
  try{
    if(/^\/studio\/access\/[A-Za-z0-9_-]{20,100}\/?$/.test(path))return Response.redirect(new URL('/studio/',url).href,302);
    if(path==='/studio'||path==='/studio/'){const assetReq=new Request(new URL('/studio.html',url),request);const res=await env.ASSETS.fetch(assetReq);return new Response(res.body,{status:res.status,headers:{...Object.fromEntries(res.headers),'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow'}})}
    if(path==='/studio/preview/'){const id=(url.searchParams.get('id')||'preview').replace(/[^\w-]/g,'').slice(0,80)||'preview';const p={id,title:'본문 미리보기',category:'일상',teaser:'',beforeContent:'',afterContent:'',gateLine:'',views:0,fadeHeight:180,date:'',tags:[]};return html(articlePage(p,[],true),200,{'X-Robots-Tag':'noindex, nofollow'})}
    if(path.startsWith('/api/')&&!['/api/ssul_posts'].includes(path)&&!/^\/api\/stories\//.test(path)){if(!['GET','HEAD'].includes(request.method)){const origin=request.headers.get('Origin');if(origin&&origin!==url.origin)return json({error:'Forbidden'},403)}return await studioApi(request,path)}
    if(path==='/api/ssul_posts'){
      if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':url.origin,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'apikey,content-type'}});
      try{if(request.method==='POST'){if(request.headers.get('Origin')&&request.headers.get('Origin')!==url.origin)return new Response('Forbidden',{status:403});const body=await request.json();if(body.action!=='view'||!body.id)return new Response('Invalid request',{status:400});const out=await data(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'view',id:dbId(body.id)})});return Response.json(out,{headers:{'Cache-Control':'no-store'}})}if(request.method!=='GET')return new Response('Method not allowed',{status:405});const query=new URLSearchParams(url.search);if(query.has('id'))query.set('id',dbId(query.get('id')));const out=await data(API+'?'+query.toString());if(out.posts)out.posts=out.posts.map(siteContent);if(out.post)out.post=siteContent(out.post);return Response.json(out,{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({ok:false,error:'게시글 서버 연결 실패'},{status:502})}
    }
    const view=path.match(/^\/api\/stories\/([^/]+)\/view\/?$/);if(view){if(request.method!=='POST')return new Response('Method not allowed',{status:405,headers:{Allow:'POST'}});const origin=request.headers.get('Origin');if(origin&&origin!==url.origin)return new Response('Forbidden',{status:403});const id=dbId(decodeURIComponent(view[1]));if(!/^[\w-]{1,100}$/.test(id))return new Response('Invalid story ID',{status:400});try{const out=await data(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'view',id})});return Response.json(out,{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({ok:false,error:'조회수를 갱신하지 못했습니다.'},{status:502})}}
    if(path==='/post'||path==='/post.html'){const id=url.searchParams.get('id');if(!id)return Response.redirect(url.origin+'/',302);return Response.redirect(new URL(storyUrl(id),url.origin).href,302)}
    if(path==='/stories.json'&&request.method==='GET'){try{const result=await data(API+'?limit=100');return json((result.posts||[]).map(siteContent))}catch{return json({error:'게시글 서버 연결 실패'},502)}}
    const article=path.match(/^\/stories\/([^/]+)\/?$/),home=path==='/'||/^\/page\/\d+\/?$/.test(path);if(!home&&!article)return env.ASSETS.fetch(request);if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405,headers:{Allow:'GET, HEAD'}});
    try{const result=await data(API+'?limit=100'),posts=(result.posts||[]).map(siteContent);if(home){const page=path==='/'?1:Number(path.split('/')[2]),out=listPage(posts,page,Object.fromEntries(url.searchParams));return html(request.method==='HEAD'?'':out||shell('글을 찾을 수 없어요','<main id="main" class="wrap empty-page"><h1>페이지를 찾을 수 없어요.</h1><a href="/">전체 글</a></main>'),out?200:404)}const id=dbId(decodeURIComponent(article[1]));let post=posts.find(p=>dbId(p.id)===id);if(!post){try{post=siteContent((await data(API+'?id='+encodeURIComponent(id))).post)}catch{return html(shell('글을 찾을 수 없어요','<main id="main" class="wrap empty-page"><h1>글을 찾을 수 없어요.</h1><a href="/">전체 글</a></main>'),404)}}return html(request.method==='HEAD'?'':articlePage(post,posts,false))}catch(error){console.error('ssul public backend:',error.message);return html(shell('연결 확인','<main id="main" class="wrap empty-page"><h1>게시글 서버에 연결하지 못했어요.</h1><p>잠시 후 새로고침해 주세요.</p><a href="/">다시 시도</a></main>'),503)}
  }catch(error){console.error('ssul worker:',error?.message||error);const status=Number(error?.status)||500;return path.startsWith('/api/')?json({error:error?.message||'요청을 처리하지 못했어요.'},status):html('<!doctype html><meta charset="utf-8"><title>오류</title><p>요청을 처리하지 못했어요.</p>',status)}
}};
