const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cfg=window.SSUL_CONFIG;
const API_HEADERS={apikey:cfg.publishableKey};
const state={posts:[],category:'전체',query:'',sort:'new',view:'list',hero:0,auto:true,remote:true};
const tones=['linear-gradient(130deg,#251f1b,#9b613f)','linear-gradient(130deg,#31242a,#a85c67)','linear-gradient(130deg,#24322d,#4f9070)','linear-gradient(130deg,#252733,#53608d)','linear-gradient(130deg,#352d20,#b58a43)','linear-gradient(130deg,#25333a,#5f8c94)'];
function fallback(){return window.SSULPAN_DATA?.SEEDS||[]}
function normalize(p,i=0){return {...p,id:String(p.id),views:Number(p.views??p.view_count??0),date:p.date||(p.publishedAt||p.published_at||'').slice(0,10),tags:Array.isArray(p.tags)?p.tags:[],hashtags:Array.isArray(p.hashtags)?p.hashtags:[],tone:tones[(Number(p.id)||i)%tones.length]}}
async function loadPosts(){try{const r=await fetch(cfg.publicApi,{headers:API_HEADERS,cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'API');state.posts=(d.posts||[]).map(normalize);state.remote=true;$('#connectionNotice').classList.add('hidden')}catch(e){state.posts=fallback().map(normalize);state.remote=false;const n=$('#connectionNotice');n.classList.remove('hidden');n.textContent='서버 연결에 실패해 복구본을 표시하고 있어요.';console.error(e)}renderAll()}
function categories(){return ['전체',...new Set(state.posts.map(p=>p.category))]}
function list(){let x=[...state.posts];if(state.category!=='전체')x=x.filter(p=>p.category===state.category);if(state.query){const q=state.query.toLowerCase();x=x.filter(p=>[p.title,p.teaser,p.category,...p.tags,...p.hashtags].join(' ').toLowerCase().includes(q))}if(state.sort==='views')x.sort((a,b)=>b.views-a.views);else if(state.sort==='old')x.sort((a,b)=>(a.date||'').localeCompare(b.date||''));else x.sort((a,b)=>(b.date||'').localeCompare(a.date||''));return x}
function hrefFor(p){return `./post.html?id=${encodeURIComponent(p.id)}`}
function openPost(p){location.href=hrefFor(p)}
function renderFeed(){const items=list();$('#feedTitle').textContent=state.category==='전체'?(state.query?`검색 결과 · ${state.query}`:'전체 글'):state.category;$('#postCount').textContent=items.length;const chips=$('#chips');chips.innerHTML='';categories().forEach(c=>{const b=document.createElement('button');b.textContent=c;b.className=c===state.category?'on':'';b.onclick=()=>{state.category=c;renderFeed();syncNav()};chips.append(b)});const g=$('#grid');g.className='grid'+(state.view==='list'?' list':'');g.innerHTML='';items.forEach(p=>{const el=document.createElement('a');el.className='card';el.href=hrefFor(p);const bg=p.thumbnailUrl?`url('${p.thumbnailUrl}') center/cover`:p.tone;el.innerHTML=`<div class="thumb" style="background:${bg}"><div><span>${p.category}</span><strong>${p.title}</strong></div></div><div class="card-body"><div class="card-meta"><span class="eyebrow">${p.category}</span><span>조회 ${p.views.toLocaleString()}</span></div><h3>${p.title}</h3><p>${p.teaser}</p><div class="card-foot"><span>${p.date||''}</span><span>조회 ${p.views.toLocaleString()}</span></div></div>`;g.append(el)});if(!items.length)g.innerHTML='<div class="notice">조건에 맞는 이야기가 없습니다.</div>'}
function renderSide(){const counts={};state.posts.forEach(p=>counts[p.category]=(counts[p.category]||0)+1);$('#board').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="board-row"><button class="pill" data-side="${k}">${k}</button><b>${v}</b></div>`).join('');$$('[data-side]').forEach(b=>b.onclick=()=>{state.category=b.dataset.side;renderFeed();syncNav()});const popular=[...state.posts].sort((a,b)=>b.views-a.views).slice(0,5);$('#popular').innerHTML=popular.map(p=>`<a class="popular" href="${hrefFor(p)}"><b>${p.title}</b><small>${p.category} · 조회 ${p.views.toLocaleString()}</small></a>`).join('');const tags=[...new Set(state.posts.flatMap(p=>p.tags))];$('#tags').innerHTML=tags.map(t=>`<button data-tag="${t}">#${t}</button>`).join('');$$('[data-tag]').forEach(b=>b.onclick=()=>{state.query=b.dataset.tag;$('#searchInput').value=state.query;renderFeed()});$('#categorySections').innerHTML=categories().filter(c=>c!=='전체').map(c=>`<section><div class="cat-head"><h3>${c}</h3><button data-jump="${c}">${c} 전체 글</button></div>${state.posts.filter(p=>p.category===c).slice(0,2).map(p=>`<a class="cat-story" href="${hrefFor(p)}">${p.title}</a>`).join('')}</section>`).join('');$$('[data-jump]').forEach(b=>b.onclick=()=>{state.category=b.dataset.jump;renderFeed();syncNav()})}
function heroItems(){return [...state.posts].sort((a,b)=>b.views-a.views||String(b.date).localeCompare(String(a.date))).slice(0,3)}
function renderHero(){const h=heroItems();if(!h.length)return;state.hero=(state.hero+h.length)%h.length;const p=h[state.hero];const hero=$('#heroBg');hero.style.background=p.thumbnailUrl?`url('${p.thumbnailUrl}') center/cover`:p.tone;$('#heroCat').textContent=p.category;$('#heroTitle').textContent=p.title;$('#heroTeaser').textContent=p.teaser;$('#heroCount').textContent=`${state.hero+1} / ${h.length}`;$('#heroTitle').onclick=()=>openPost(p);$('#heroTitle').title='글 읽기'}
function syncNav(){$$('[data-cat]').forEach(b=>b.classList.toggle('on',b.dataset.cat===state.category));$$('[data-sort]').forEach(b=>b.classList.toggle('on',b.dataset.sort===state.sort))}
function renderAll(){renderFeed();renderSide();renderHero();syncNav()}
$('#searchForm').onsubmit=e=>{e.preventDefault();state.query=$('#searchInput').value.trim();state.category='전체';renderFeed();syncNav();document.querySelector('#feed').scrollIntoView({behavior:'smooth',block:'start'})};
$$('[data-sort]').forEach(b=>b.onclick=()=>{state.sort=b.dataset.sort;renderFeed();syncNav()});
$('#cardBtn').onclick=()=>{state.view='card';$('#cardBtn').classList.add('on');$('#listBtn').classList.remove('on');renderFeed()};
$('#listBtn').onclick=()=>{state.view='list';$('#listBtn').classList.add('on');$('#cardBtn').classList.remove('on');renderFeed()};
$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;state.query='';$('#searchInput').value='';renderFeed();syncNav()});
$('#popularNav').onclick=()=>{state.category='전체';state.sort='views';renderFeed();syncNav();document.querySelector('#feed').scrollIntoView({behavior:'smooth'})};
$('#allPostsNav').onclick=()=>{state.category='전체';state.query='';$('#searchInput').value='';renderFeed();syncNav();document.querySelector('#feed').scrollIntoView({behavior:'smooth'})};
$('#heroPrev').onclick=()=>{state.hero--;renderHero()};$('#heroNext').onclick=()=>{state.hero++;renderHero()};
$('#heroAuto').onclick=()=>{state.auto=!state.auto;$('#heroAuto').textContent=state.auto?'일시정지':'자동재생'};
setInterval(()=>{if(state.auto&&state.posts.length){state.hero++;renderHero()}},5000);
loadPosts();
