const posts=[
{id:1,category:'직장생활',title:'퇴사도 안 했는데, 내 후임이 출근했다',excerpt:'월요일 아침, 처음 보는 사람이 내 옆에 앉았다. 그러더니 웃으면서 말했다. “인수인계 받으러 왔습니다.”',views:1284,date:'2026-09-10',tags:['회사썰','직장생활','인수인계'],tone:'linear-gradient(130deg,#251f1b,#9b613f)',body:['월요일 아침이었다. 평소처럼 자리에 앉아 메일을 켰는데 낯선 사람이 내 옆 빈자리에 앉았다.','그 사람은 노트북을 꺼내더니 너무 자연스럽게 말했다. “인수인계 받으러 왔습니다.”','나는 아직 퇴사 이야기를 꺼낸 적도 없었다. 그 순간부터 사무실의 모든 대화가 다르게 들리기 시작했다.']},
{id:2,category:'인간관계',title:'내 결혼식 못 온다던 친구가, 다른 식장 사진에 찍혔다',excerpt:'가족 일 때문에 못 온다던 12년 친구. 그런데 내 결혼식 다음 날, 다른 신부 옆에서 웃고 있는 사진을 봤다.',views:1107,date:'2026-09-09',tags:['친구썰','결혼식','인간관계'],tone:'linear-gradient(130deg,#31242a,#a85c67)',body:['12년을 친구로 지낸 사람이었다. 내 결혼식에는 가족 일이 생겨 정말 미안하다며 오지 못한다고 했다.','서운했지만 이해하려 했다. 그런데 다음 날 우연히 본 사진 한 장에서 그 친구가 다른 결혼식장에 있었다.','사진 속 표정이 너무 밝아서, 오히려 무슨 말을 해야 할지 모르겠더라.']},
{id:3,category:'일상',title:'중고거래하러 갔더니 판매자가 엄마였다',excerpt:'사진 속 스탠드가 익숙했다. 설마 했는데, 약속 장소에 익숙한 사람이 서 있었다.',views:968,date:'2026-09-08',tags:['일상썰','중고거래','가족썰'],tone:'linear-gradient(130deg,#24322d,#4f9070)',body:['중고거래 앱에서 마음에 드는 스탠드를 발견했다. 사진을 보는데 어딘가 너무 익숙했다.','약속 장소에 도착했더니 판매자가 우리 엄마였다. 서로 한동안 말없이 쳐다봤다.','엄마는 결국 그냥 가져가라고 했고, 나는 왜 집에 있던 걸 돈 주고 사려고 했는지 설명해야 했다.']},
{id:4,category:'직장생활',title:'신입이 회의록 한 줄을 읽자, 팀장 얼굴이 굳었다',excerpt:'팀장이 사람들 앞에서 내 실수라고 했다. 그때 입사한 지 한 달 된 신입이 노트북을 돌렸다.',views:823,date:'2026-09-07',tags:['신입','직장인공감','회사썰'],tone:'linear-gradient(130deg,#252733,#53608d)',body:['회의가 시작되자 팀장은 일정이 밀린 이유가 내 실수 때문이라고 말했다.','나는 반박할 타이밍을 놓쳤다. 그때 신입이 조용히 회의록을 띄웠다.','거기에는 팀장이 직접 일정 변경을 지시한 날짜와 내용이 그대로 남아 있었다.']},
{id:5,category:'인간관계',title:'생일 선물 대신, 친구가 반나절을 비워줬다',excerpt:'필요한 거 있냐는 말에 아무것도 없다고 했다. 친구는 토요일 오전을 비워 두라고 했다.',views:711,date:'2026-09-06',tags:['친구썰','생일선물','인간관계'],tone:'linear-gradient(130deg,#352d20,#b58a43)',body:['생일이 다가오자 친구가 필요한 게 있냐고 물었다. 정말 갖고 싶은 게 없어서 아무것도 없다고 했다.','친구는 선물 대신 토요일 오전을 비워 두라고 했다.','그날 우리는 미뤄 둔 병원 예약도 가고, 머리도 자르고, 점심도 먹었다. 생각보다 오래 기억에 남는 선물이었다.']},
{id:6,category:'일상',title:'매일 엘리베이터를 잡아주던 사람이 안 보였다',excerpt:'같은 시간에 출근하던 이웃. 인사밖에 해본 적 없는데, 며칠째 안 보이니 신경이 쓰였다.',views:594,date:'2026-09-05',tags:['일상썰','이웃','출근'],tone:'linear-gradient(130deg,#243036,#548497)',body:['매일 아침 같은 시간에 엘리베이터를 타는 이웃이 있었다. 먼저 도착하면 늘 문을 잡아줬다.','그런데 어느 날부터 보이지 않았다. 인사밖에 해본 적 없는데 이상하게 계속 신경이 쓰였다.','며칠 뒤 다시 마주쳤을 때 괜히 반가워서 평소보다 먼저 인사를 건넸다.']}
];
const state={category:'전체',query:'',sort:'new',view:'card',hero:0,auto:true};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const savedViews=JSON.parse(localStorage.getItem('ssulpan.views')||'{}');posts.forEach(p=>p.views+=(savedViews[p.id]||0));
function categories(){return ['전체',...new Set(posts.map(p=>p.category))]}
function filtered(){let list=[...posts];if(state.category!=='전체')list=list.filter(p=>p.category===state.category);if(state.query){const q=state.query.toLowerCase();list=list.filter(p=>[p.title,p.excerpt,p.category,...p.tags].join(' ').toLowerCase().includes(q))}if(state.sort==='views')list.sort((a,b)=>b.views-a.views);else list.sort((a,b)=>state.sort==='old'?a.date.localeCompare(b.date):b.date.localeCompare(a.date));return list}
function renderChips(){const host=$('#categoryChips');host.innerHTML='';categories().forEach(c=>{const b=document.createElement('button');b.textContent=c;b.classList.toggle('is-active',state.category===c);b.onclick=()=>{state.category=c;syncNav();renderFeed()};host.append(b)})}
function renderFeed(){renderChips();const list=filtered();$('#feedTitle').textContent=state.category==='전체'?(state.query?`검색 결과 · ${state.query}`:'전체 글'):state.category;const grid=$('#postGrid');grid.className='post-grid'+(state.view==='list'?' list':'');grid.innerHTML='';$('#emptyState').hidden=!!list.length;list.forEach(p=>{const el=document.createElement('article');el.className='post-card';el.innerHTML=`<div class="thumb" style="background:${p.tone}"><span>${p.category}</span></div><div class="post-inner"><span class="eyebrow">${p.category}</span><h3>${p.title}</h3><p>${p.excerpt}</p><div class="post-foot"><span>${p.date}</span><span>조회 ${p.views.toLocaleString()}</span></div></div>`;el.onclick=()=>openPost(p);grid.append(el)})}
function renderSidebar(){const counts={};posts.forEach(p=>counts[p.category]=(counts[p.category]||0)+1);$('#boardCounts').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="board-row"><button class="nav-btn" data-side-category="${k}">${k}</button><b>${v}</b></div>`).join('');$$('[data-side-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.sideCategory;renderFeed();syncNav();scrollTo({top:$('#main').offsetTop,behavior:'smooth'})});const popular=[...posts].sort((a,b)=>b.views-a.views).slice(0,5);$('#popularList').innerHTML=popular.map(p=>`<div class="popular-item" data-post="${p.id}"><b>${p.title}</b><small>${p.category} · 조회 ${p.views.toLocaleString()}</small></div>`).join('');$$('[data-post]').forEach(x=>x.onclick=()=>openPost(posts.find(p=>p.id===+x.dataset.post)));const tags=[...new Set(posts.flatMap(p=>p.tags))];$('#tagCloud').innerHTML=tags.map(t=>`<button data-tag="${t}">#${t}</button>`).join('');$$('[data-tag]').forEach(b=>b.onclick=()=>{state.query=b.dataset.tag;$('#searchInput').value=state.query;renderFeed()})}
function renderHero(){const hero=[...posts].sort((a,b)=>b.views-a.views).slice(0,3);const p=hero[state.hero%hero.length];$('#heroTrack').style.background=p.tone;$('#heroCategory').textContent=p.category;$('#heroTitle').textContent=p.title;$('#heroExcerpt').textContent=p.excerpt;$('#heroCount').textContent=`${state.hero+1} / ${hero.length}`;$('#heroTitle').onclick=()=>openPost(p)}
function syncNav(){$$('.nav-btn[data-category]').forEach(b=>b.classList.toggle('is-active',b.dataset.category===state.category))}
function openPost(p){const increments=JSON.parse(localStorage.getItem('ssulpan.views')||'{}');increments[p.id]=(increments[p.id]||0)+1;localStorage.setItem('ssulpan.views',JSON.stringify(increments));p.views+=1;$('#articleCategory').textContent=p.category;$('#articleTitle').textContent=p.title;$('#articleMeta').textContent=`${p.date} · 조회 ${p.views.toLocaleString()}`;$('#articleBody').innerHTML=p.body.map(x=>`<p>${x}</p>`).join('');$('#articleTags').innerHTML=p.tags.map(t=>`<span>#${t}</span>`).join('');$('#articleDialog').showModal();renderSidebar()}
$('#closeArticle').onclick=()=>$('#articleDialog').close();$('#articleDialog').addEventListener('click',e=>{if(e.target===$('#articleDialog'))$('#articleDialog').close()});
$('#searchForm').onsubmit=e=>{e.preventDefault();state.query=$('#searchInput').value.trim();renderFeed()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderFeed()};$('#cardView').onclick=()=>{state.view='card';$('#cardView').classList.add('is-active');$('#listView').classList.remove('is-active');renderFeed()};$('#listView').onclick=()=>{state.view='list';$('#listView').classList.add('is-active');$('#cardView').classList.remove('is-active');renderFeed()};
$$('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;state.query='';$('#searchInput').value='';syncNav();renderFeed()});$$('[data-popular]').forEach(b=>b.onclick=()=>{state.sort='views';$('#sortSelect').value='views';state.category='전체';syncNav();renderFeed();scrollTo({top:$('#main').offsetTop+350,behavior:'smooth'})});$('#showPopular').onclick=()=>{$('[data-popular]').click()};
$('#prevHero').onclick=()=>{state.hero=(state.hero+2)%3;renderHero()};$('#nextHero').onclick=()=>{state.hero=(state.hero+1)%3;renderHero()};$('#toggleAuto').onclick=()=>{state.auto=!state.auto;$('#toggleAuto').textContent=state.auto?'일시정지':'자동재생';$('#toggleAuto').setAttribute('aria-pressed',String(!state.auto))};setInterval(()=>{if(state.auto){state.hero=(state.hero+1)%3;renderHero()}},5000);
renderFeed();renderSidebar();renderHero();
