import {siteHeader,siteFooter,communityPage,formatViews} from './ssul-community.mjs';
export {siteHeader,siteFooter};
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paras=t=>String(t||'').split(/\n\s*\n/).filter(x=>x.trim()).map(x=>`<p>${escape(x)}</p>`).join('');
const chevron='<span aria-hidden="true">›</span>';
const pageURL=n=>n===1?'/':`/page/${n}/`;
export function shell(title,body,script='',options={}) {return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} | 썰판</title><meta name="description" content="직장생활, 인간관계, 일상의 이야기."><meta name="theme-color" content="#fd582b"><meta name="robots" content="noindex,nofollow"><link rel="icon" type="image/png" sizes="1254x1254" href="/favicon.png?v=ssulpan-1"><link rel="apple-touch-icon" href="/favicon.png?v=ssulpan-1"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/community.css"><link rel="stylesheet" href="/studio-entry.css"></head><body id="top" class="${options.home?'community-home':''}"><a class="skip" href="#main">본문 바로가기</a>${siteHeader(options)}${body}${siteFooter()}${script}<script src="/studio-entry.js" defer></script></body></html>`;}
export function listPage(posts,page=1,options={}){const result=communityPage(posts,page,options);if(!result)return null;return shell(result.heading,result.body,(result.headerOptions.view==='cards'?'<script src="/cover.js" defer></script><script src="/thumbnails.js" defer></script>':'')+'<script src="/community.js" defer></script>',{...result.headerOptions,home:true});}
export function articlePage(s,posts=[],preview=false,ad=null){
  const i=posts.findIndex(x=>x.id===s.id),previous=posts[(i-1+posts.length)%posts.length],next=posts[(i+1)%posts.length];
  const related=posts.length>1?`<nav class="related" aria-label="이전 글과 다음 글">${[['이전 글',previous,'prev'],['다음 글',next,'next']].map(([label,p,rel])=>`<div class="related-item"><h2>${label}</h2><a href="/stories/${escape(p.id)}/" rel="${rel}"><span>${escape(p.title)}</span>${chevron}</a></div>`).join('')}</nav>`:'';
  let advert='';if(ad){try{const u=new URL(ad.url);if(u.protocol==='https:'&&['link.coupang.com','www.coupang.com','coupa.ng'].includes(u.hostname)&&!u.username&&!u.password)advert=`<aside class="ad"><small>광고 · 쿠팡 파트너스</small><a href="${escape(u.href)}" target="_blank" rel="sponsored noopener noreferrer">${escape(ad.title)}</a><p>이 게시물은 쿠팡 파트너스 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다.</p></aside>`;}catch{}}
  const data=JSON.stringify({id:s.id,fadeHeight:s.fadeHeight||180,trackViews:!preview}).replaceAll('<','\\u003c');
  return shell(s.title||'본문 미리보기',`<main id="main" class="article-wrap"><a class="back" href="${pageURL(Math.max(0,Math.floor(i/20))+1)}">‹ 전체 글</a><article><header class="article-heading"><span class="article-category">${escape(s.category)}</span><h1>${escape(s.title)}</h1><div class="article-meta">썰판${preview?'':' · 조회 <span id="story-view-count">'+formatViews(s.views)+'</span>'}</div></header><div class="article-body" id="reader"><div id="opening">${paras(s.beforeContent)}</div><section class="read-gate" id="read-gate" style="--fade-height:${s.fadeHeight||180}px" ${s.afterContent?'':'hidden'} aria-label="이어 읽기"><div class="fade-sample" id="fade-sample" aria-hidden="true" inert>${paras(s.afterContent.split(/\n\s*\n/).slice(0,2).join('\n\n'))}</div><div class="gate-copy"><h2 id="gate-heading">${escape(s.gateLine||'그다음 이야기가 궁금하다면?')}</h2><button class="continue-button" id="continue-reading" aria-controls="continuation" aria-expanded="false">계속 읽기</button><span class="gate-preview-note">현재는 광고 없이 이어 읽을 수 있어요.</span></div></section><div id="continuation" hidden tabindex="-1">${paras(s.afterContent)}<div class="story-end">이야기 끝</div></div><p class="reader-status" id="reader-status" role="status"></p></div>${advert}</article>${related}</main><noscript><style>#read-gate{display:none}#continuation[hidden]{display:block!important}</style></noscript>`,`<script type="application/json" id="reader-data">${data}</script><script src="/reader.js" defer></script>`);
}
