const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='ssulpan.studio.drafts';
const seedDrafts=[{id:'published-1',status:'게시됨',title:'퇴사도 안 했는데, 내 후임이 출근했다',category:'직장생활',seed:'월요일 아침 처음 보는 사람이 옆자리에 앉아 인수인계를 받으러 왔다고 말한다.',previewText:'월요일 아침, 처음 보는 사람이 내 옆에 앉았다. 그러더니 웃으면서 말했다. “인수인계 받으러 왔습니다.”',afterText:'나는 아직 퇴사 이야기를 꺼낸 적도 없었다. 그 순간부터 사무실의 모든 대화가 다르게 들리기 시작했다.',rewriteGuide:'',memo:'화자: 기존 직원 / 낯선 사람: 후임으로 보이는 인물 / 팀장 반응이 핵심',continueLine:'신입이 화면을 돌린 이유.',tags:'#회사썰 #직장생활 #인수인계',gradient:180}];
let drafts=JSON.parse(localStorage.getItem(KEY)||'null')||seedDrafts;let currentId=drafts[0]?.id||null;
function saveAll(){localStorage.setItem(KEY,JSON.stringify(drafts));$('#saveStatus').textContent='로컬 저장됨'}
function fields(){return{title:$('#title').value.trim(),category:$('#category').value,seed:$('#seed').value,previewText:$('#previewText').value,afterText:$('#afterText').value,rewriteGuide:$('#rewriteGuide').value,memo:$('#memo').value,continueLine:$('#continueLine').value,tags:$('#tags').value,gradient:+$('#gradient').value}}
function load(d){if(!d)return;currentId=d.id;$('#title').value=d.title||'';$('#category').value=d.category||'직장생활';$('#seed').value=d.seed||'';$('#previewText').value=d.previewText||'';$('#afterText').value=d.afterText||'';$('#rewriteGuide').value=d.rewriteGuide||'';$('#memo').value=d.memo||'';$('#continueLine').value=d.continueLine||'';$('#tags').value=d.tags||'';$('#gradient').value=d.gradient||180;updateCounts();$('#gradientValue').textContent=`${$('#gradient').value}px`;$('#saveStatus').textContent=d.status||'초안'}
function refreshSelect(){const sel=$('#storySelect');sel.innerHTML=drafts.map(d=>`<option value="${d.id}">${d.status||'초안'} · ${d.title||'제목 없음'}</option>`).join('');if(currentId)sel.value=currentId}
function updateCounts(){$('#previewCount').textContent=`${$('#previewText').value.length.toLocaleString()}자`;$('#afterCount').textContent=`${$('#afterText').value.length.toLocaleString()}자`}
function upsert(status){const data=fields();let d=drafts.find(x=>x.id===currentId);if(!d){d={id:`draft-${Date.now()}`};drafts.unshift(d);currentId=d.id}Object.assign(d,data,{status:status||d.status||'초안',updatedAt:new Date().toISOString()});saveAll();refreshSelect();return d}
$('#storySelect').onchange=e=>load(drafts.find(d=>d.id===e.target.value));$('#newDraft').onclick=()=>{currentId=null;['title','seed','previewText','afterText','rewriteGuide','memo','continueLine','tags'].forEach(id=>$('#'+id).value='');$('#category').value='직장생활';$('#gradient').value=180;updateCounts();$('#gradientValue').textContent='180px';$('#saveStatus').textContent='새 원고'};
['previewText','afterText'].forEach(id=>$('#'+id).addEventListener('input',updateCounts));$('#gradient').oninput=e=>$('#gradientValue').textContent=`${e.target.value}px`;
$$('[data-copy]').forEach(b=>b.onclick=async()=>{const text=$('#'+b.dataset.copy).value;await navigator.clipboard.writeText(text);b.textContent='복사됨';setTimeout(()=>b.textContent='내용 복사',900)});
async function callAI(payload){const r=await fetch('/api/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`API ${r.status}`);return data}
$('#generate').onclick=async()=>{const status=$('#generateStatus');const data=fields();if(!data.seed.trim()){status.textContent='원본 소재를 먼저 입력해 주세요.';return}status.textContent='생성 중…';$('#generate').disabled=true;try{const out=await callAI({mode:'generate',title:data.title,category:data.category,seed:data.seed,memo:data.memo});$('#title').value=out.title||data.title;$('#previewText').value=out.previewText||'';$('#afterText').value=out.afterText||'';$('#continueLine').value=out.continueLine||'';$('#tags').value=(out.tags||[]).map(t=>t.startsWith('#')?t:'#'+t).join(' ');updateCounts();upsert('초안');status.textContent='생성 완료'}catch(e){status.textContent=`생성 실패: ${e.message}`}finally{$('#generate').disabled=false}};
$$('[data-rewrite]').forEach(b=>b.onclick=async()=>{const id=b.dataset.rewrite;const original=$('#'+id).value;if(!original.trim())return;const old=b.textContent;b.disabled=true;b.textContent='다시 쓰는 중…';try{const out=await callAI({mode:'rewrite',section:id,original,guide:$('#rewriteGuide').value,title:$('#title').value,category:$('#category').value,memo:$('#memo').value});$('#'+id).value=out.text||original;updateCounts();upsert('초안')}catch(e){alert(`다시 쓰기 실패: ${e.message}`)}finally{b.disabled=false;b.textContent=old}});
$('#saveDraft').onclick=()=>upsert('초안');$('#publishDraft').onclick=()=>{const d=upsert('게시됨');$('#saveStatus').textContent='게시 상태로 저장됨';alert(`“${d.title||'제목 없음'}”을 게시 상태로 저장했습니다. 현재 복구본에서는 실제 공개 목록 동기화는 다음 단계에서 Supabase 연결 후 활성화합니다.`)};
$('#viewPublished').onclick=()=>location.href='/';
$('#exportDraft').onclick=()=>{const d=upsert();const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ssulpan-${(d.title||'draft').replace(/[\\/:*?"<>|]/g,'_')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
refreshSelect();load(drafts[0]);
