const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const paras=s=>String(s||'').split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).map(x=>`<p>${esc(x).replace(/\n/g,'<br>')}</p>`).join('');
const tags=s=>String(s||'').split(/\s+/).filter(Boolean).map(t=>`<span>${esc(t)}</span>`).join('');
const css='<link rel="stylesheet" href="/site.css">';
export function shell(title,body,extra=''){
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · 썰판</title>${css}${extra}</head><body><a class="skip" href="#main">본문 바로가기</a>${body}</body></html>`;
}
function header(){return `<header class="top"><div class="wrap top-row"><a class="brand" href="/">썰판</a><nav><a href="/">홈</a><a href="/?category=직장생활">직장생활</a><a href="/?category=인간관계">인간관계</a><a href="/?category=일상">일상</a><a href="/?sort=popular">인기글</a></nav><form class="search" action="/" method="get"><input name="q" placeholder="이야기 검색" aria-label="이야기 검색"><button>검색</button></form></div></header>`;}
function card(s){return `<a class="story-card" href="/stories/${encodeURIComponent(s.id)}/"><div class="story-thumb"><span>${esc(s.category)}</span></div><div><small>${esc(s.category)}</small><h3>${esc(s.title)}</h3><p>${esc(s.teaser)}</p><em>조회 ${Number(s.views||0).toLocaleString('ko-KR')}</em></div></a>`;}
export function listPage(posts,page=1){
  const size=6,total=Math.max(1,Math.ceil(posts.length/size));if(page<1||page>total)return null;const slice=posts.slice((page-1)*size,page*size),popular=[...posts].sort((a,b)=>(b.views||0)-(a.views||0)).slice(0,5),cats=['직장생활','인간관계','일상'];const hero=posts.slice(0,3);
  const body=`${header()}<main id="main" class="wrap"><section class="hero" data-hero aria-label="추천 글"><span class="sr-only">추천 글</span>${hero.map((s,i)=>`<a class="hero-slide${i?' is-hidden':''}" href="/stories/${s.id}/" data-slide="${i}"><div><small>${esc(s.category)}</small><h1>${esc(s.title)}</h1><p>${esc(s.teaser)}</p></div></a>`).join('')}<div class="hero-controls"><button type="button" data-prev>이전</button><span data-count>1 / ${hero.length}</span><button type="button" data-next>다음</button><button type="button" data-toggle>일시정지</button></div></section><div class="layout"><section><div class="section-head"><div><small>전체 글</small><h2>전체 글</h2></div><div class="view-controls"><a href="/?sort=new">최신순</a><a href="/?sort=old">오래된순</a><a href="/?sort=popular">조회수순</a><button type="button" data-card>카드형 보기</button><button type="button" data-list>목록형 보기</button></div></div><div class="chips"><a href="/">전체</a>${cats.map(c=>`<a href="/?category=${encodeURIComponent(c)}">${c}</a>`).join('')}</div><div class="story-grid" data-grid>${slice.map(card).join('')}</div><div class="pagination"><a href="${page>1?`/page/${page-1}/`:'#'}">‹ 이전</a><span>${page}</span><a href="${page<total?`/page/${page+1}/`:'#'}">다음 ›</a></div><p class="summary">전체 ${posts.length}편 · ${page} / ${total} 페이지</p></section><aside><section class="side"><h3>게시판</h3>${cats.map(c=>`<p><a href="/?category=${encodeURIComponent(c)}">${c}</a><b>${posts.filter(s=>s.category===c).length}</b></p>`).join('')}</section><section class="side"><h3>인기글</h3>${popular.map(s=>`<a class="popular" href="/stories/${s.id}/"><b>${esc(s.title)}</b><small>${esc(s.category)} · 조회 ${Number(s.views||0).toLocaleString('ko-KR')}</small></a>`).join('')}</section><section class="side"><h3>태그</h3><div class="tag-cloud">${[...new Set(posts.flatMap(s=>String(s.hashtags||'').split(/\s+/).filter(Boolean)))].map(t=>`<span>${esc(t)}</span>`).join('')}</div></section></aside></div></main><footer><div class="wrap"><b>썰판</b><a href="#main">맨 위로</a></div></footer><script src="/public.js" defer></script>`;
  return shell('이야기 모음',body);
}
export function articlePage(s,posts=[],preview=false,ad){
  const idx=posts.findIndex(x=>x.id===s.id),next=posts.length?posts[(idx+1+posts.length)%posts.length]:null;const gate=esc(s.gateLine||'계속 읽어보세요.');const notice=ad?'광고 확인 후 이어 읽을 수 있어요.':'현재는 광고 없이 이어 읽을 수 있어요.';
  const body=`${preview?'':header()}<main id="main" class="reader" data-story="${esc(s.id)}"><a class="back" href="/">← 전체 글</a><small class="category">${esc(s.category)}</small><h1 data-title>${esc(s.title)}</h1><p class="teaser" data-teaser>${esc(s.teaser||'')}</p><section class="reader-before" data-before>${paras(s.beforeContent)}</section><div class="fade" data-fade style="height:${Math.max(80,Math.min(300,Number(s.fadeHeight)||180))}px"></div><h2 class="gate" data-gate>${gate}</h2><button class="continue" type="button" data-continue>계속 읽기</button><p class="ad-note">${esc(notice)}</p><section class="reader-after" data-after hidden>${paras(s.afterContent)}</section>${preview?'':`<hr><section class="next"><small>다음 글</small>${next?`<a href="/stories/${next.id}/">${esc(next.title)} <b>›</b></a>`:''}</section><p class="admin-links"><a href="/studio/?story=${encodeURIComponent(s.id)}">이 글의 인스타 원고 · 본문 끊기 설정</a></p>`}<div class="tag-cloud" data-tags>${tags(s.hashtags)}</div></main>${preview?'':`<footer class="reader-footer"><b>썰집</b><a href="/studio/?story=${encodeURIComponent(s.id)}">채널 제작실</a></footer>`}<script>window.__SSEOLZIP_PREVIEW__=${preview?'true':'false'};</script><script src="/reader.js" defer></script>`;
  return shell(s.title,body,preview?'<meta name="robots" content="noindex,nofollow">':'');
}
